title: [Lovlesh | Experienced Software Engineer, JavaScript]
description: [Lovlesh Pokra - Experienced software engineer with over a decade of expertise in software development, frontend architecture, application security and compliance. React.js, JavaScript]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
