title: Lovlesh | Experienced Software Engineer, JavaScript, React, Node
description: Experienced software engineer with over a decade of expertise in software development, frontend architecture, application security and compliance.
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  another_url: https://medium.com/@lovleshpokra
